{% set build = 0 %}
{% set rev = '6fc3566' %}
{% set req = {'openmpi':'>=1.8.8'} %}
{% set version = '2.0.0' %}

package:
  name: mpi4py
  version: {{version}}.git.{{rev}}

about:
  home: https://bitbucket.org/mpi4py/
  license: 'BSD (https://bitbucket.org/mpi4py/mpi4py/src/master/LICENSE.rst)'
  summary: 'Python bindings for MPI.'

source:
  git_url: https://bitbucket.org/mpi4py/mpi4py
  git_rev: {{rev}}

requirements:
  build:
    - python
    - cython >=0.22
    - openmpi {{req[mpi]}}

  run:
    - python
    - openmpi {{req[mpi]}}

build:
  number: {{build}}
  string: py{{py}}_openmpi188_{{build}}
  script: python setup.py build_exe install

